### ISSUE TITLE
AR Magazines

### ISSUE THREAD

**Issue by gurdyboy** [RHSMODS/statusquo#206]
**Phase 1:**

Magazines:

- [ ] 20Rnd USGI Magazine (PuFu)

- [ ] 30Rnd USGI Magazine (PuFu)
- [ ] 30Rnd USGI EPM Magazine (PuFu)

- [ ] 30Rnd PMAG GEN M3 (Window)

**Phase 2:**

Magazines:

- [ ] 30Rnd PMAG GEN M3

- [ ] 40Rnd PMAG GEN M3

- [ ] 60Rnd PMAG D-60 GEN M3

Attachments:

- [ ] Magazine Puller (PuFu)
- [ ] PMAG Ranger Plate (PuFu)
