### ISSUE TITLE
Manta Rail Covers and Accessories (for M27 / M38)

### ISSUE THREAD

**Issue by ajvorobiev** [RHSMODS/statusquo#49]
**Phase 1:**

- [ ] M27IAR Kit
- [ ] Cross Clip
- [ ] Vertical Grip Sleeve 1" w/ End Caps
- [ ] 6" Low Profile Wire Routing Rail Guard
- [ ] 2.75" Micro Pocket Panel
- [ ] Vertical Grip Sleeve 1"
- [ ] Vertical Grip Sleeve 1.25"
